/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'skillhub';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ACCOUNT = 'assets/images/account.svg';
  static const String COURSES = 'assets/images/courses.svg';
  static const String FILTER = 'assets/images/filter.svg';
  static const String GOOGLE_LOGO = 'assets/images/google_logo.svg';
  static const String HOME = 'assets/images/home.svg';
  static const String LANGUAGE = 'assets/images/language.svg';
  static const String MEETUP = 'assets/images/meetup.svg';
  static const String MESSAGE = 'assets/images/message.svg';
  static const String ONBOARDING_IMAGE = 'assets/images/onboarding_image.svg';
  static const String PAINTING = 'assets/images/painting.svg';
  static const String SEARCH = 'assets/images/search.svg';
  static const String TODAY = 'assets/images/today.svg';
  static const String TODAY2 = 'assets/images/today2.svg';
  static const String USER = 'assets/images/user.svg';
}
