// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVtK1TBX3GVlwbhJDzkncw5lttUjp6lbk',
    appId: '1:914853760538:web:964f5eb5076d91bc954ba3',
    messagingSenderId: '914853760538',
    projectId: 'skillhub-345fb',
    authDomain: 'skillhub-345fb.firebaseapp.com',
    storageBucket: 'skillhub-345fb.appspot.com',
    measurementId: 'G-KWKMQ8LJZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYSJWchbBol8VB-UUGnOnBgv2r6NSVTzA',
    appId: '1:914853760538:android:47678d296c5ed65b954ba3',
    messagingSenderId: '914853760538',
    projectId: 'skillhub-345fb',
    storageBucket: 'skillhub-345fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2T5YNNQH3fAmVbbJg9CuIJGyVm_vj9s',
    appId: '1:914853760538:ios:dba7a3923cf6215c954ba3',
    messagingSenderId: '914853760538',
    projectId: 'skillhub-345fb',
    storageBucket: 'skillhub-345fb.appspot.com',
    androidClientId: '914853760538-afaage0k13o2cs91ia1694alh1obfeur.apps.googleusercontent.com',
    iosClientId: '914853760538-5vu8v2bvtp7eagr38u2ihoe0df2l3kur.apps.googleusercontent.com',
    iosBundleId: 'com.app.skillhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB2T5YNNQH3fAmVbbJg9CuIJGyVm_vj9s',
    appId: '1:914853760538:ios:dba7a3923cf6215c954ba3',
    messagingSenderId: '914853760538',
    projectId: 'skillhub-345fb',
    storageBucket: 'skillhub-345fb.appspot.com',
    androidClientId: '914853760538-afaage0k13o2cs91ia1694alh1obfeur.apps.googleusercontent.com',
    iosClientId: '914853760538-5vu8v2bvtp7eagr38u2ihoe0df2l3kur.apps.googleusercontent.com',
    iosBundleId: 'com.app.skillhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVtK1TBX3GVlwbhJDzkncw5lttUjp6lbk',
    appId: '1:914853760538:web:78f053894133153c954ba3',
    messagingSenderId: '914853760538',
    projectId: 'skillhub-345fb',
    authDomain: 'skillhub-345fb.firebaseapp.com',
    storageBucket: 'skillhub-345fb.appspot.com',
    measurementId: 'G-4N30XS8JSY',
  );

}